DROP TABLE IF EXISTS `Rack`;
DROP TABLE IF EXISTS `LoadBalancer`;
DROP TABLE IF EXISTS `Server`;
DROP TABLE IF EXISTS `VirtualMachine`;
DROP TABLE IF EXISTS `Application`;
DROP TABLE IF EXISTS `runon`;
DROP TABLE IF EXISTS `Category`;
DROP TABLE IF EXISTS `Belong`;
DROP TABLE IF EXISTS `DatabaseServer`;
DROP TABLE IF EXISTS `User`;


CREATE TABLE Rack (
    Rid VARCHAR(10) PRIMARY KEY,
    名称 VARCHAR(20),
    位置 VARCHAR(25),
    容量 VARCHAR(10)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE LoadBalancer (
    LBid VARCHAR(10) PRIMARY KEY,
    名称 VARCHAR(20),
    IP地址 VARCHAR(25),
    端口 VARCHAR(15),
    负载分发算法 VARCHAR(20),
    SSL加速 VARCHAR(5),
    会话保持 VARCHAR(5),
    Rid VARCHAR(10),
    FOREIGN KEY (Rid) REFERENCES Rack(Rid) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Server (
    Sid VARCHAR(10) PRIMARY KEY,
    名称 VARCHAR(20),
    IP地址 VARCHAR(25),
    操作系统 VARCHAR(15),
    处理器类型 VARCHAR(10),
    内存容量 VARCHAR(10),
    Rid VARCHAR(10),
    FOREIGN KEY (Rid) REFERENCES Rack (Rid) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE VirtualMachine (
    VMid VARCHAR(10) PRIMARY KEY,
    名称 VARCHAR(20),
    版本 VARCHAR(15),
    访问控制 VARCHAR(5),
    认证配置 VARCHAR(5),
    容错设置 VARCHAR(5),
    Sid VARCHAR(10),
    FOREIGN KEY (Sid) REFERENCES Server (Sid) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE DatabaseServer (
    DBSid VARCHAR(10) PRIMARY KEY,
    名称 VARCHAR(20),
    IP地址 VARCHAR(25),
    DBMS类型 VARCHAR(20),
    版本 VARCHAR(15),
    处理器类型 VARCHAR(10),
    内存容量 VARCHAR(10)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Application (
    Aid VARCHAR(10) PRIMARY KEY,
    名称 VARCHAR(20),
    版本 VARCHAR(15),
    开发者 VARCHAR(20),
    简述 VARCHAR(50),
    占用空间大小 VARCHAR(10),
    DBSid VARCHAR(10),
    FOREIGN KEY (DBSid) REFERENCES DatabaseServer (DBSid) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE runon (
    Aid VARCHAR(10),
    VMid VARCHAR(10),
    PRIMARY KEY (Aid, VMid),
    FOREIGN KEY (Aid) REFERENCES Application (Aid) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (VMid) REFERENCES VirtualMachine (VMid) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Category (
    Cid VARCHAR(10) PRIMARY KEY,
    名称 VARCHAR(20),
    说明 VARCHAR(50)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Belong (
    Aid VARCHAR(10),
    Cid VARCHAR(10),
    PRIMARY KEY (Aid, Cid),
    FOREIGN KEY (Aid) REFERENCES Application (Aid) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (Cid) REFERENCES Category (Cid) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE Replicia (
    复制品DBSid VARCHAR(10),
    被复制DBSid VARCHAR(10),
    PRIMARY KEY (复制品DBSid, 被复制DBSid),
    FOREIGN KEY (复制品DBSid) REFERENCES DatabaseServer (DBSid) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (被复制DBSid) REFERENCES DatabaseServer (DBSid) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE User (
    Uid VARCHAR(10) PRIMARY KEY,
    性别 VARCHAR(5),
    年龄 VARCHAR(5),
    邮箱 VARCHAR(25)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE useof (
    Uid VARCHAR(10),
    Aid VARCHAR(10),
    PRIMARY KEY (Uid, Aid),
    FOREIGN KEY (Uid) REFERENCES User (Uid) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (Aid) REFERENCES Application (Aid) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;











